import os
from typing import Literal

from datasets import Dataset, DatasetDict
from tokenizers import Tokenizer
from tokenizers.models import BPE, Unigram, WordLevel, WordPiece
from tokenizers.pre_tokenizers import ByteLevel, Whitespace
from tokenizers.trainers import BpeTrainer, UnigramTrainer, WordLevelTrainer, WordPieceTrainer
from transformers import PreTrainedTokenizerFast

# TODO: Replace example, generated by AI token txt files with actual ones
# ! Current Data for token is AI


def train_tokenizer(
    dataset: Dataset | DatasetDict,
    tokenization_type: Literal["bpe", "wordpiece", "unigram", "wordlevel", "char"] = "bpe",
    output_file_directory: str = "data/tokenizer.json",
    vocab_size: int = 5000,
):
    if tokenization_type == "bpe":
        tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
        trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], vocab_size=vocab_size)
        tokenizer.pre_tokenizer = Whitespace()
    elif tokenization_type == "wordpiece":
        tokenizer = Tokenizer(WordPiece(unk_token="[UNK]"))
        trainer = WordPieceTrainer(
            special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], vocab_size=vocab_size
        )
        tokenizer.pre_tokenizer = Whitespace()
    elif tokenization_type == "unigram":
        tokenizer = Tokenizer(Unigram())
        trainer = UnigramTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], vocab_size=vocab_size)
        tokenizer.pre_tokenizer = Whitespace()
    elif tokenization_type == "wordlevel":
        tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))
        trainer = WordLevelTrainer(
            special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], vocab_size=vocab_size
        )
        tokenizer.pre_tokenizer = Whitespace()
    elif tokenization_type == "char":
        tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
        trainer = BpeTrainer(special_tokens=["[UNK]", "[CLS]", "[SEP]", "[PAD]", "[MASK]"], vocab_size=vocab_size)
        tokenizer.pre_tokenizer = ByteLevel()

    tokenizer.train_from_iterator(iterator=dataset["train"]["Sequence"], trainer=trainer)

    directory = os.path.dirname(output_file_directory)
    if not os.path.exists(directory):
        os.makedirs(directory)

    tokenizer.save(output_file_directory)

    tokenizer = PreTrainedTokenizerFast(tokenizer_file=output_file_directory)

    return tokenizer
